const assert = require('node:assert/strict')
const vscode = require('vscode')
const { dirname, join } = require('node:path')
const { existsSync, mkdirSync, renameSync, rmSync, writeFileSync } = require('node:fs')

async function eventually(run, message) {
  for (let attempt = 0; attempt < 40; attempt++) { const value = await run(); if (value) return value; await new Promise((resolve) => setTimeout(resolve, 100)) }
  assert.fail(message)
}
exports.run = async function run() {
  const root = join(vscode.workspace.workspaceFolders[0].uri.fsPath, 'apps', 'api', 'src')
  const scopeFile = join(root, 'routes', '+scope.ts')
  const file = join(root, 'routes', '[id]', '+server.ts')
  const helperFile = join(root, 'auth.ts'); writeFileSync(helperFile, `export const getUser=()=>({id:'u'})`)
  writeFileSync(scopeFile, `import {defineScope} from '@southneuhof/sprindle'\r\nimport {getUser} from '../auth'\r\n// unrelated user comment: café 🚀\r\nexport default defineScope({\r\n  context:()=>({user:getUser()}),\r\n})\r\n`)
  writeFileSync(file, `import {defineRoute} from '@southneuhof/sprindle'\r\n\r\nexport const GET=defineRoute({\r\n  action:({params,context})=>({id:params.id,user:context.user.id}),\r\n})\r\n`)
  const ordinary = await vscode.workspace.openTextDocument(join(root, 'ordinary.ts'))
  await vscode.window.showTextDocument(ordinary)
  assert.equal(ordinary.languageId, 'typescript')
  await eventually(() => vscode.languages.getDiagnostics(ordinary.uri).some((item) => item.code === 2322 && item.source === 'ts'), 'ordinary TypeScript diagnostics were not preserved')
  const documentPromise = vscode.workspace.openTextDocument(file)
  const otherPromise = vscode.workspace.openTextDocument(join(vscode.workspace.workspaceFolders[0].uri.fsPath, 'apps', 'other', 'src', 'routes', '+server.ts'))
  const [document, otherDocument] = await Promise.all([documentPromise, otherPromise, vscode.workspace.openTextDocument(scopeFile)]); await vscode.window.showTextDocument(document)
  await eventually(() => document.languageId === 'sprindle-typescript', 'route language did not activate after first route creation')
  assert.equal(otherDocument.languageId, 'typescript', 'the single-project server took over a second project')
  await vscode.extensions.getExtension('southneuhof.sprindle-language').activate()
  const badFile = join(root, 'routes', 'bad', '+server.ts'); mkdirSync(dirname(badFile), { recursive: true }); writeFileSync(badFile, `import {defineRoute} from '@southneuhof/sprindle'\nexport const GET=defineRoute({action:({c})=>c.req.notARealMethod()})`)
  const badDocument = await vscode.workspace.openTextDocument(badFile); await vscode.window.showTextDocument(badDocument)
  await eventually(() => vscode.languages.getDiagnostics(badDocument.uri).some((item) => item.code === 2339), 'packaged Hono context became any')
  const badEdit = new vscode.WorkspaceEdit(); badEdit.replace(badDocument.uri, new vscode.Range(0, 0, badDocument.lineCount, 0), badDocument.getText().replace('notARealMethod()', "header('authorization')")); await vscode.workspace.applyEdit(badEdit)
  await eventually(() => !vscode.languages.getDiagnostics(badDocument.uri).some((item) => item.code === 2339), 'packaged dependency diagnostic did not recover')
  await vscode.commands.executeCommand('workbench.action.closeActiveEditor')
  const usersScope = join(root, 'routes', 'users', '+scope.ts'); mkdirSync(dirname(usersScope), { recursive: true }); writeFileSync(usersScope, `import {defineScope} from '@southneuhof/sprindle';import {z} from 'zod';export default defineScope({entity:{schemas:{select:z.object({id:z.string(),name:z.string()})}}})`)
  const usersRoute = join(root, 'routes', 'users', '+server.ts'); writeFileSync(usersRoute, `import {list} from '@southneuhof/sprindle';export const GET=list({run:()=>({data:[{id:'1',missing:'x'}],total:1})})`)
  const usersDocument = await vscode.workspace.openTextDocument(usersRoute); await vscode.window.showTextDocument(usersDocument)
  await eventually(() => vscode.languages.getDiagnostics(usersDocument.uri).some((item) => item.code === 2322), 'packaged Zod record fields became any')
  await vscode.commands.executeCommand('workbench.action.closeActiveEditor')
  await vscode.window.showTextDocument(document)
  const helper = await vscode.workspace.openTextDocument(helperFile); await vscode.window.showTextDocument(helper)
  const helperEdit = new vscode.WorkspaceEdit(); helperEdit.replace(helper.uri, new vscode.Range(0, 0, helper.lineCount, 0), `export const getUser=()=>({name:'u'})`); await vscode.workspace.applyEdit(helperEdit)
  await eventually(() => vscode.languages.getDiagnostics(document.uri).some((item) => item.code === 2339), 'unsaved imported helper change did not update route diagnostics')
  await vscode.commands.executeCommand('workbench.action.revertAndCloseActiveEditor')
  await eventually(() => !vscode.languages.getDiagnostics(document.uri).some((item) => item.code === 2339), 'closing the imported helper did not restore route types')
  await vscode.window.showTextDocument(document)
  const parameterPosition = document.positionAt(document.getText().indexOf('params.id') + 7)
  const completions = await vscode.commands.executeCommand('vscode.executeCompletionItemProvider', document.uri, parameterPosition)
  assert.ok(completions.items.some((item) => item.label === 'id'))
  const hovers = await vscode.commands.executeCommand('vscode.executeHoverProvider', document.uri, parameterPosition)
  assert.ok(hovers.some((item) => item.contents.some((content) => String(content.value).includes('string'))))
  const contextPosition = document.positionAt(document.getText().indexOf('context.user') + 8)
  const definitions = await vscode.commands.executeCommand('vscode.executeDefinitionProvider', document.uri, contextPosition)
  assert.equal(definitions.length, 1)
  assert.equal(definitions[0].uri.fsPath, scopeFile)
  const scopeSource = (await vscode.workspace.openTextDocument(scopeFile)).getText()
  assert.equal(scopeSource.slice((await vscode.workspace.openTextDocument(scopeFile)).offsetAt(definitions[0].range.start), (await vscode.workspace.openTextDocument(scopeFile)).offsetAt(definitions[0].range.end)), 'user')

  let scope = await vscode.workspace.openTextDocument(scopeFile)
  await vscode.window.showTextDocument(scope)
  await eventually(() => scope.languageId === 'sprindle-typescript', 'scope language did not activate')
  const parentEdit = new vscode.WorkspaceEdit(); parentEdit.replace(scope.uri, new vscode.Range(0, 0, scope.lineCount, 0), scope.getText().replace('user:', 'account:')); await vscode.workspace.applyEdit(parentEdit)
  assert.ok(scope.getText().includes('account:'))
  await eventually(async () => {
    const items = await vscode.commands.executeCommand('vscode.executeCompletionItemProvider', document.uri, contextPosition)
    return items.items.some((item) => item.label === 'account') && !items.items.some((item) => item.label === 'user')
  }, 'unsaved parent edit did not update child completion')
  await vscode.commands.executeCommand('workbench.action.revertAndCloseActiveEditor')
  await eventually(async () => {
    const items = await vscode.commands.executeCommand('vscode.executeCompletionItemProvider', document.uri, contextPosition)
    return items.items.some((item) => item.label === 'user') && !items.items.some((item) => item.label === 'account')
  }, 'closing the unsaved parent did not discard its overlay')

  scope = await vscode.workspace.openTextDocument(scopeFile)
  await assert.rejects(vscode.commands.executeCommand('vscode.executeDocumentRenameProvider', document.uri, contextPosition, 'account'), /complete references cannot be proven/)
  assert.ok(scope.getText().includes('user:'))
  assert.ok(document.getText().includes('context.user'))

  const added = join(root, 'routes', '[id]', 'child', '[childId]', '+server.ts'); mkdirSync(dirname(added), { recursive: true }); writeFileSync(added, `import {defineRoute} from '@southneuhof/sprindle'\nexport const GET=defineRoute({action:({params})=>params.childId})`)
  let addedDocument = await vscode.workspace.openTextDocument(added); await vscode.window.showTextDocument(addedDocument)
  const addedPosition = addedDocument.positionAt(addedDocument.getText().indexOf('params.childId') + 7)
  const addedCompletions = await vscode.commands.executeCommand('vscode.executeCompletionItemProvider', addedDocument.uri, addedPosition)
  assert.ok(addedCompletions.items.some((item) => item.label === 'childId' && item.label !== 'id'))
  await vscode.commands.executeCommand('workbench.action.closeActiveEditor')

  const moved = join(root, 'routes', 'public', '[slug]', '+server.ts'); mkdirSync(dirname(moved), { recursive: true }); renameSync(added, moved)
  const movedDocument = await vscode.workspace.openTextDocument(moved); await vscode.window.showTextDocument(movedDocument)
  const movedPosition = movedDocument.positionAt(movedDocument.getText().indexOf('params.childId') + 7)
  const movedCompletions = await vscode.commands.executeCommand('vscode.executeCompletionItemProvider', movedDocument.uri, movedPosition)
  assert.ok(movedCompletions.items.some((item) => item.label === 'slug'))
  assert.ok(!movedCompletions.items.some((item) => item.label === 'childId' || item.label === 'id'))
  await eventually(() => vscode.languages.getDiagnostics(movedDocument.uri).some((item) => item.code === 2339), 'move kept the old parameter type')
  await vscode.commands.executeCommand('workbench.action.closeActiveEditor')
  rmSync(dirname(moved), { recursive: true })
  await eventually(() => !existsSync(moved), 'route delete did not complete')
  assert.deepEqual(vscode.languages.getDiagnostics(vscode.Uri.file(added)), [])
}
